// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgYJjrfXWFyg1pV8loRsII7nZceXgu7BM',
    appId: '1:278405072217:web:8a19932c916e246137b848',
    messagingSenderId: '278405072217',
    projectId: 'offermath-f4399',
    authDomain: 'offermath-f4399.firebaseapp.com',
    storageBucket: 'offermath-f4399.firebasestorage.app',
    measurementId: 'G-J69X663PGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1VFZEGjAL24fK7XP18eqj3ZWGQKOJDcQ',
    appId: '1:278405072217:android:305092e9e4f6cc2737b848',
    messagingSenderId: '278405072217',
    projectId: 'offermath-f4399',
    storageBucket: 'offermath-f4399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXvgMTOGfV6VhVIfJX1JKjdQGQK3_Lx_w',
    appId: '1:278405072217:ios:1b6f81c23f99175e37b848',
    messagingSenderId: '278405072217',
    projectId: 'offermath-f4399',
    storageBucket: 'offermath-f4399.firebasestorage.app',
    iosBundleId: 'com.example.offermath',
  );
}
